# Generated by Django 4.2 on 2025-01-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('P', 'Planta'), ('E', 'Eléctrico'), ('A', 'Agua'), ('F', 'Fuego'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
